"use client";

import React, { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CodeSnippetViewer from "@/components/CodeSnippetViewer";
import SaveButton from "@/components/SaveButton";
import { useGetCheatsheetsQuery } from "@/lib/api/courseApi";
import { TECH_STACKS } from "@/lib/tutorialData";
import {
  Sparkles,
  Search,
  Loader2,
  Download,
  FileText,
  Printer,
} from "lucide-react";

/** Generate and trigger a print-to-PDF for a single cheatsheet */
function downloadCheatsheetPdf(cs, techName) {
  const printWindow = window.open("", "_blank", "width=900,height=700");
  if (!printWindow) return;

  const snippetsHtml = (cs.snippets || [])
    .map(
      (snip, i) => `
      <div style="margin-bottom:28px;">
        <p style="font-size:11px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:0.08em;margin:0 0 8px 0;">
          ${i + 1}. ${snip.name || "Snippet"}
        </p>
        <pre style="background:#1e1e2e;color:#cdd6f4;padding:16px 20px;border-radius:12px;font-size:12px;font-family:'Fira Code',Courier,monospace;white-space:pre-wrap;word-break:break-word;line-height:1.6;margin:0;">${escapeHtml(snip.code || "")}</pre>
      </div>`,
    )
    .join("");

  printWindow.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${cs.title} — asif.to Cheatsheet</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&family=Fira+Code&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', sans-serif; background: #fff; color: #18181b; padding: 40px; max-width: 800px; margin: auto; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none !important; }
    }
    header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #e4e4e7; }
    .logo { font-size: 18px; font-weight: 900; color: #18181b; }
    .logo span { color: #2563eb; }
    .badge { background: #dbeafe; color: #1d4ed8; font-size: 10px; font-weight: 700; padding: 4px 12px; border-radius: 100px; text-transform: uppercase; letter-spacing: 0.1em; }
    h1 { font-size: 26px; font-weight: 900; color: #18181b; margin-bottom: 8px; line-height: 1.2; }
    .desc { font-size: 13px; color: #71717a; margin-bottom: 32px; line-height: 1.6; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e4e4e7; font-size: 11px; color: #a1a1aa; text-align: center; }
    .print-btn { display: inline-flex; align-items: center; gap: 8px; background: #2563eb; color: white; border: none; padding: 10px 20px; border-radius: 100px; font-weight: 700; font-size: 13px; cursor: pointer; margin-bottom: 28px; }
    .print-btn:hover { background: #1d4ed8; }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">
    🖨️ Print / Save as PDF
  </button>

  <header>
    <div class="logo"><img src="/logo.png" alt="asif.to" style="width:24px;height:24px;border-radius:6px;vertical-align:middle;margin-right:8px;" />asif<span>.to</span></div>
    <div class="badge">${techName || cs.techId} Cheatsheet</div>
  </header>

  <h1>${cs.title}</h1>
  ${cs.description ? `<p class="desc">${cs.description}</p>` : ""}

  ${snippetsHtml}

  <footer>
    Generated by asif.to — Your coding reference, always ready.
  </footer>
</body>
</html>`);

  printWindow.document.close();
}

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export default function CheatsheetsPage() {
  const [selectedTech, setSelectedTech] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");

  const { data, isLoading } = useGetCheatsheetsQuery(
    selectedTech ? { techId: selectedTech } : undefined,
  );

  const CHEATSHEETS = data?.data || [];

  const filteredCheatsheets = CHEATSHEETS.filter((cs) => {
    const matchesSearch =
      !searchQuery ||
      cs.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      cs.snippets?.some(
        (s) =>
          s.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
          s.code?.toLowerCase().includes(searchQuery.toLowerCase()),
      );
    return matchesSearch;
  });

  return (
    <div className="min-h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950 text-foreground transition-colors duration-300 pb-24 sm:pb-12">
      <Header />

      <main className="flex-1 w-full max-w-4xl mx-auto px-4 sm:px-6 pt-20 sm:pt-24 flex flex-col gap-6">
        {/* Header Title */}
        <div className="flex flex-col gap-2">
          <div className="inline-flex items-center gap-1.5 px-3.5 py-1 rounded-full bg-blue-600 text-white text-xs font-bold w-fit shadow-md shadow-blue-500/20">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Instant Syntax Reference Hub</span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-foreground">
            Coding Cheatsheets & Syntax Reference
          </h1>
          <p className="text-xs sm:text-sm text-zinc-500 dark:text-zinc-400 font-medium">
            Quickly lookup React hooks, Next.js routes, Express middleware,
            MongoDB aggregation pipelines, and Tailwind CSS utilities.
          </p>
        </div>

        {/* Search Bar */}
        <div className="relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-400" />
          <input
            type="text"
            placeholder="Search syntax (e.g. useState, revalidatePath, populate, flex...)"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-11 pr-4 py-3.5 rounded-full bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white placeholder:text-zinc-400 text-xs sm:text-sm shadow-md focus:outline-none focus:ring-4 focus:ring-blue-400/30 font-semibold"
          />
        </div>

        {/* Tech Stack Filter Pills */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
          <button
            onClick={() => setSelectedTech(null)}
            className={`px-4 py-2 rounded-full text-xs font-bold whitespace-nowrap transition-all ${
              !selectedTech
                ? "bg-blue-600 text-white shadow-md shadow-blue-500/25"
                : "bg-white dark:bg-zinc-900 text-zinc-600 dark:text-zinc-300 hover:text-foreground shadow-sm"
            }`}
          >
            All Cheatsheets
          </button>
          {TECH_STACKS.map((tech) => (
            <button
              key={tech.id}
              onClick={() => setSelectedTech(tech.id)}
              className={`px-4 py-2 rounded-full text-xs font-bold whitespace-nowrap transition-all ${
                selectedTech === tech.id
                  ? "bg-blue-600 text-white shadow-md shadow-blue-500/25"
                  : "bg-white dark:bg-zinc-900 text-zinc-600 dark:text-zinc-300 hover:text-foreground shadow-sm"
              }`}
            >
              {tech.name}
            </button>
          ))}
        </div>

        {/* Loading */}
        {isLoading && (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
          </div>
        )}

        {/* Cheatsheets List */}
        {!isLoading && (
          <div>
            {filteredCheatsheets.length === 0 ? (
              <div className="text-center py-20 rounded-[2.5rem] bg-white dark:bg-zinc-900/90 shadow-sm border border-zinc-200/80 dark:border-zinc-800/80">
                <FileText className="w-10 h-10 text-zinc-300 dark:text-zinc-700 mx-auto mb-3" />
                <p className="font-bold text-sm text-muted-foreground">
                  No cheatsheets found.
                </p>
                <p className="text-xs text-zinc-400 mt-1">
                  Try a different search or tech filter.
                </p>
              </div>
            ) : (
              <div className="bg-white dark:bg-zinc-900 rounded-[2.5rem] border border-zinc-200/80 dark:border-zinc-800/80 shadow-sm overflow-hidden divide-y divide-zinc-100 dark:divide-zinc-800/80">
                {filteredCheatsheets.map((cs, idx) => {
                  const tech = TECH_STACKS.find((t) => t.id === cs.techId);

                  return (
                    <div
                      key={cs._id || cs.id}
                      className={`p-6 sm:p-8 space-y-4 hover:bg-zinc-50/50 dark:hover:bg-zinc-800/40 transition-colors ${
                        idx === 0 ? "rounded-t-[2.5rem]" : ""
                      } ${idx === filteredCheatsheets.length - 1 ? "rounded-b-[2.5rem]" : ""}`}
                    >
                      {/* Cheatsheet Header Row */}
                      <div className="flex items-start justify-between gap-3 flex-wrap">
                        <div className="flex items-center gap-3 flex-wrap">
                          <span
                            className={`font-bold px-3 py-1 rounded-full text-xs ${tech?.badgeBg || "bg-blue-500/10 text-blue-600"}`}
                          >
                            {tech?.name || cs.techId} Cheatsheet
                          </span>
                          <span className="text-xs text-zinc-400 font-medium">
                            {cs.snippets?.length ?? 0} snippets
                          </span>
                        </div>

                        <div className="flex items-center gap-2">
                          <SaveButton
                            itemId={cs._id}
                            itemType="cheatsheet"
                            label="Save"
                            size="sm"
                          />
                          <button
                            onClick={() =>
                              downloadCheatsheetPdf(cs, tech?.name)
                            }
                            className="flex items-center gap-1.5 px-4 py-2 rounded-full bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 text-foreground text-xs font-bold transition-all active:scale-95 shadow-sm cursor-pointer"
                            title="Download as PDF"
                          >
                            <Download className="w-3.5 h-3.5 text-blue-500" />
                            <span>Download PDF</span>
                          </button>
                        </div>
                      </div>

                      {/* Title & Description */}
                      <div>
                        <h2 className="text-xl sm:text-2xl font-black text-foreground">
                          {cs.title}
                        </h2>
                        {cs.description && (
                          <p className="text-xs sm:text-sm text-zinc-500 dark:text-zinc-400 mt-1 font-medium leading-relaxed">
                            {cs.description}
                          </p>
                        )}
                      </div>

                      {/* Code Snippets */}
                      <div className="space-y-4 pt-2">
                        {(cs.snippets || []).map((snip, snipIdx) => (
                          <div key={snipIdx} className="space-y-1.5">
                            <span className="text-xs font-extrabold text-foreground tracking-wide block">
                              {snip.name}
                            </span>
                            <CodeSnippetViewer
                              code={snip.code}
                              language={snip.language || "javascript"}
                              title={snip.name}
                            />
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </main>

      <Footer />
    </div>
  );
}
