"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ChevronDown, Edit3, FilePlus2, Loader2, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { coursesApi, interviewQuestionsApi, quizApi } from "@/lib/api";
import { Button } from "@/components/ui";
import { ConfirmDialog } from "@/components/confirm-dialog";
import AdminFormShell from "@/components/AdminFormShell";
import { AdminContent, AdminFilters, AdminPagination, AdminSearch } from "@/components/admin";

const difficultyStyles = { easy: "bg-emerald-50 text-emerald-700", medium: "bg-amber-50 text-amber-700", hard: "bg-red-50 text-red-700" };
export default function QuestionsPage() {
  const [questions, setQuestions] = useState([]); const [courses, setCourses] = useState([]); const [loading, setLoading] = useState(true); const [courseId, setCourseId] = useState("all"); const [type, setType] = useState("all"); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 }); const [deleteTarget, setDeleteTarget] = useState(null); const [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { setLoading(true); const params = { type, page, limit: 20, ...(courseId !== "all" && { courseId }) }; const [response, courseResponse] = await Promise.all([quizApi.listAll(params), courses.length ? null : coursesApi.listAll()]); if (response.success) { setQuestions(response.data?.data || []); setPagination(response.data?.pagination || { page: 1, pages: 1, total: 0 }); } else toast.error(response.error || "Unable to load questions"); if (courseResponse?.success) setCourses(courseResponse.data?.data?.data || courseResponse.data?.data || []); setLoading(false); }, [courseId, courses.length, page, type]);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return query ? questions.filter((item) => [item.question, item.answer, item.explanation, ...(item.options || [])].filter(Boolean).some((value) => value.toLowerCase().includes(query))) : questions; }, [questions, search]);
  const filter = (setter) => (event) => { setter(event.target.value); setPage(1); };
  const remove = async () => { setDeleting(true); const response = await (deleteTarget.type === "interview" ? interviewQuestionsApi : quizApi).delete(deleteTarget._id); if (response.success) { toast.success("Question deleted"); setDeleteTarget(null); load(); } else toast.error(response.error || "Unable to delete question"); setDeleting(false); };
  return <AdminFormShell eyebrow="Learning / Assessment" title="Question bank" description="Manage quiz/practice and detailed interview questions from one collection." actions={<Link href="/quiz/new"><Button><Plus className="mr-2 h-4 w-4" /> New question</Button></Link>}>
    <AdminFilters><AdminSearch value={search} onChange={setSearch} placeholder="Search questions and answers" /><div className="relative md:w-52"><select value={type} onChange={filter(setType)} className="h-12 w-full appearance-none rounded-2xl border-0 bg-zinc-100 px-4 dark:bg-zinc-900"><option value="all">All types</option><option value="quiz">Quiz / practice</option><option value="interview">Interview</option></select><ChevronDown className="pointer-events-none absolute right-4 top-4 h-4 w-4" /></div><div className="relative md:w-64"><select value={courseId} onChange={filter(setCourseId)} className="h-12 w-full appearance-none rounded-2xl border-0 bg-zinc-100 px-4 dark:bg-zinc-900"><option value="all">All courses</option>{courses.map((course) => <option key={course._id} value={course._id}>{course.title}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-4 h-4 w-4" /></div></AdminFilters>
    <AdminContent><div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="border-b border-zinc-200 bg-zinc-50 text-xs uppercase text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900"><tr><th className="px-5 py-3">Question</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Course</th><th className="px-5 py-3">Difficulty</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-zinc-100 dark:divide-zinc-800">{loading ? <tr><td colSpan="5" className="py-16"><Loader2 className="mx-auto h-5 w-5 animate-spin text-blue-600" /></td></tr> : visible.length === 0 ? <tr><td colSpan="5" className="py-16 text-center text-zinc-500"><FilePlus2 className="mx-auto mb-3 h-8 w-8" />No questions match these filters.</td></tr> : visible.map((item) => <tr key={item._id} className="hover:bg-zinc-50 dark:hover:bg-zinc-900/40"><td className="max-w-xl px-5 py-4"><p className="font-semibold text-zinc-900 dark:text-white">{item.question}</p><p className="mt-1 line-clamp-1 text-xs text-zinc-400">{item.type === "interview" ? item.answer : `Correct: ${item.options?.[item.correctIndex] || "—"}`}</p></td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold capitalize text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{item.type}</span></td><td className="px-5 py-4 text-zinc-600 dark:text-zinc-300">{item.type === "interview" ? item.course?.title : (item.courses || []).map((course) => course.title).join(", ")}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${difficultyStyles[item.difficulty]}`}>{item.difficulty}</span></td><td className="px-5 py-4"><div className="flex justify-end"><Link href={`/quiz/${item._id}/edit`}><Button variant="ghost" size="icon"><Edit3 className="h-4 w-4" /></Button></Link><Button variant="ghost" size="icon" onClick={() => setDeleteTarget(item)}><Trash2 className="h-4 w-4 text-red-500" /></Button></div></td></tr>)}</tbody></table></div><AdminPagination page={pagination.page} pages={pagination.pages} total={pagination.total} itemLabel="questions" onPageChange={setPage} /></AdminContent>
    <ConfirmDialog isOpen={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} onConfirm={remove} loading={deleting} variant="destructive" title="Delete question?" description="This permanently removes the selected question." confirmText="Delete" />
  </AdminFormShell>;
}
