"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Check, Loader2, Save } from "lucide-react";
import { toast } from "sonner";
import Editor from "@/components/editor/Editor";
import AdminFormShell, { formAsideClass, formSectionClass } from "@/components/forms/AdminFormShell";
import { Button, Input, Label, Textarea } from "@/components/ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { coursesApi, interviewQuestionsApi, quizApi } from "@/lib/api";
import FollowUpQuestionPicker from "@/components/editor/FollowUpQuestionPicker";

const initialForm = { type: "quiz", question: "", courseIds: [], course: "", options: ["", "", "", ""], correctIndex: 0, explanation: "", quizEnabled: true, flashcardEnabled: true, flashcardAnswer: "", tag: "", answer: "", slug: "", questionType: "conceptual", tags: "", codeExample: "", expectedOutput: "", followUps: "", difficulty: "medium", status: "published" };
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export default function QuestionForm({ questionId }) {
  const searchParams = useSearchParams();
  const requestedReturnTo = searchParams.get("returnTo");
  const returnTo = requestedReturnTo?.startsWith("/") ? requestedReturnTo : "/quiz";
  const [form, setForm] = useState(initialForm);
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(Boolean(questionId));
  const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([coursesApi.listAll(), questionId ? quizApi.get(questionId) : null]).then(([courseResponse, questionResponse]) => { setCourses(courseResponse.data?.data?.data || courseResponse.data?.data || []); if (questionResponse?.success) { const item = questionResponse.data?.data; setForm({ ...initialForm, ...item, course: item.course?._id || item.course || "", courseIds: (item.courses || []).map((course) => course._id || course), options: item.options?.length === 4 ? item.options : initialForm.options, tags: (item.tags || []).join(", "), followUps: (item.followUps || []).join("\n") }); } setLoading(false); }); }, [questionId]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const updateQuestion = (value) => setForm((current) => ({ ...current, question: value, slug: current.slug || slugify(value) }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); const api = form.type === "interview" ? interviewQuestionsApi : quizApi; const payload = form.type === "interview" ? { ...form, tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean), followUps: form.followUps.split("\n").map((item) => item.trim()).filter(Boolean) } : form; const response = questionId ? await api.update(questionId, payload) : await api.create(payload); if (response.success) { toast.success(questionId ? "Question saved" : "Question created"); window.location.assign(returnTo); } else toast.error(response.error || "Unable to save question"); setSaving(false); };
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600" /></div>;
  const interview = form.type === "interview";
  return <AdminFormShell eyebrow="Learning / Question Bank" title={questionId ? "Edit question" : "Create question"} description={interview ? "Write a detailed, interview-ready answer with supporting examples." : "Create a concise quiz or practice question with one correct answer."} back={<Link href={returnTo} className="inline-flex items-center gap-2 text-sm text-zinc-500"><ArrowLeft className="h-4 w-4" /> Back to question bank</Link>} actions={<Button form="question-form" type="submit" loading={saving}><Save className="mr-2 h-4 w-4" /> Save question</Button>}>
    <form id="question-form" onSubmit={submit} className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="space-y-6"><div className={formSectionClass}><div className="space-y-2"><Label>Question</Label><Textarea required rows={4} value={form.question} onChange={(event) => updateQuestion(event.target.value)} placeholder={interview ? "Ask an interview question…" : "Write a clear multiple-choice question…"} /></div>
      {interview ? <><div className="space-y-2"><Label>Detailed answer</Label><Editor value={form.answer} onChange={(value) => update("answer", value || "")} placeholder="Write the complete interview answer…" /></div><div className="space-y-2"><Label>Code example</Label><Textarea rows={9} className="font-mono" value={form.codeExample} onChange={(event) => update("codeExample", event.target.value)} /></div><div className="space-y-2"><Label>Expected output</Label><Textarea rows={4} className="font-mono" value={form.expectedOutput} onChange={(event) => update("expectedOutput", event.target.value)} /></div></> : <><div className="space-y-3"><Label>Answer options</Label>{form.options.map((option, index) => <div key={index} className="flex gap-3"><button type="button" onClick={() => update("correctIndex", index)} className={`h-10 w-10 shrink-0 rounded-full border-2 text-sm font-bold ${form.correctIndex === index ? "border-emerald-500 bg-emerald-500 text-white" : "border-zinc-300"}`}>{index + 1}</button><Input required value={option} onChange={(event) => update("options", form.options.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder={`Option ${index + 1}`} /></div>)}</div><div className="space-y-2"><Label>Short explanation</Label><Textarea rows={4} value={form.explanation} onChange={(event) => update("explanation", event.target.value)} /></div>{form.flashcardEnabled && <><div className="space-y-2"><Label>Flashcard answer <span className="font-normal text-zinc-400">(optional override)</span></Label><Textarea rows={4} value={form.flashcardAnswer} onChange={(event) => update("flashcardAnswer", event.target.value)} /></div><div className="space-y-2"><Label>Revision tag</Label><Input value={form.tag} onChange={(event) => update("tag", event.target.value)} /></div></>}</>}
    </div></section><aside className={`${formAsideClass} self-start lg:sticky lg:top-24`}><div className="space-y-2"><Label>Question type</Label><Select disabled={Boolean(questionId)} value={form.type} onValueChange={(value) => setForm({ ...initialForm, type: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="quiz">Quiz / practice</SelectItem><SelectItem value="interview">Interview</SelectItem></SelectContent></Select>{questionId && <p className="text-xs text-zinc-500">Type cannot be changed after creation.</p>}</div>
      {interview ? <><div className="space-y-2"><Label>Course</Label><Select value={form.course} onValueChange={(value) => update("course", value)}><SelectTrigger><SelectValue placeholder="Select course" /></SelectTrigger><SelectContent>{courses.map((course) => <SelectItem key={course._id} value={course._id}>{course.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Slug</Label><Input required value={form.slug} onChange={(event) => update("slug", slugify(event.target.value))} /></div><div className="space-y-2"><Label>Interview format</Label><Select value={form.questionType} onValueChange={(value) => update("questionType", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["conceptual", "coding", "behavioral", "scenario", "debugging"].map((value) => <SelectItem key={value} value={value} className="capitalize">{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Tags</Label><Input value={form.tags} onChange={(event) => update("tags", event.target.value)} placeholder="react, hooks" /></div><FollowUpQuestionPicker course={form.course} value={form.followUps} onChange={(value) => update("followUps", value)} excludeId={questionId} /></> : <><div className="space-y-2"><Label>Courses</Label><div className="max-h-48 overflow-y-auto space-y-1.5 rounded-2xl border border-zinc-200/80 bg-zinc-50/50 p-2.5 dark:border-zinc-800/80 dark:bg-zinc-900/50">{courses.map((course) => { const selected = (form.courseIds || []).includes(course._id); return <button key={course._id} type="button" onClick={() => { const next = selected ? form.courseIds.filter((id) => id !== course._id) : [...(form.courseIds || []), course._id]; update("courseIds", next); }} className={`flex w-full items-center justify-between gap-2 rounded-xl px-3 py-2 text-xs font-semibold transition cursor-pointer ${selected ? "bg-blue-600 text-white shadow-xs" : "bg-white text-zinc-700 hover:bg-zinc-100 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"}`}><span className="truncate">{course.title}</span>{selected && <Check className="h-3.5 w-3.5 shrink-0" />}</button>; })}</div></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.quizEnabled} onChange={(event) => update("quizEnabled", event.target.checked)} /> Use in quizzes/exams</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.flashcardEnabled} onChange={(event) => update("flashcardEnabled", event.target.checked)} /> Use as flashcard</label></>}
      <div className="space-y-2"><Label>Difficulty</Label><Select value={form.difficulty} onValueChange={(value) => update("difficulty", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["easy", "medium", "hard"].map((value) => <SelectItem key={value} value={value} className="capitalize">{value}</SelectItem>)}</SelectContent></Select></div>{!interview && <div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={(value) => update("status", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="published">Published</SelectItem><SelectItem value="draft">Draft</SelectItem></SelectContent></Select></div>}</aside></form>
  </AdminFormShell>;
}
