"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
async function request(path, body, signal) {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/communications/public/${path}`, { method: body ? "POST" : "GET", headers: body ? { "Content-Type": "application/json" } : {}, body: body ? JSON.stringify(body) : undefined, signal });
  const result = await response.json(); if (!response.ok) throw new Error(result.message || "Unable to save preferences."); return result.data;
}
export default function EmailPreferences() {
  const token = useSearchParams().get("token");
  const [available, setAvailable] = useState([]), [topics, setTopics] = useState([]), [email, setEmail] = useState(""), [name, setName] = useState("");
  const [status, setStatus] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { const controller = new AbortController(); request(token ? `preferences?token=${encodeURIComponent(token)}` : "topics", null, controller.signal).then(data => { setAvailable(data.availableTopics || data.topics); if (token) { setTopics(data.topics); setEmail(data.email); setStatus(data.status); } }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [token]);
  const save = async unsubscribe => { if (busy) return; setBusy(true); setError(""); setNotice(""); try { const data = await request(token ? "preferences" : "subscribe", token ? { token, topics, unsubscribe } : { email, firstName: name, topics }); if (data.status) setStatus(data.status); setNotice(token ? unsubscribe ? "You are unsubscribed from marketing emails." : "Your email preferences are saved." : data.message); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const input = "w-full rounded-xl border border-zinc-300 bg-transparent p-3 dark:border-zinc-700";
  return <><Header /><main className="mx-auto min-h-[65vh] max-w-2xl px-4 py-16"><h1 className="text-3xl font-bold">Email preferences</h1><p className="mt-3 text-zinc-500">Choose the updates you want from asif.to. Account and security emails continue independently of these preferences.</p>{loading ? <p className="mt-6">Loading…</p> : <form className="mt-6 space-y-5" onSubmit={e => { e.preventDefault(); save(false); }}>{token ? <p>{email} · {status.toLowerCase()}</p> : <><label className="block">Email<input type="email" required className={`${input} mt-1`} value={email} onChange={e => setEmail(e.target.value)} /></label><label className="block">First name (optional)<input className={`${input} mt-1`} value={name} onChange={e => setName(e.target.value)} /></label></>}<fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-3 font-semibold">Topics</legend>{available.map(topic => <label key={topic} className="flex items-center gap-2"><input type="checkbox" checked={topics.includes(topic)} onChange={e => setTopics(values => e.target.checked ? [...values, topic] : values.filter(v => v !== topic))} />{topic}</label>)}</fieldset><p className="text-sm text-zinc-500">Selecting no topics means general updates only. You can unsubscribe at any time.</p><div className="flex flex-wrap gap-3"><button disabled={busy || !available.length} className="rounded-xl bg-blue-600 px-5 py-3 font-medium text-white disabled:opacity-50">{busy ? "Saving…" : token ? status === "PENDING" ? "Confirm subscription" : "Save preferences" : "Subscribe with email confirmation"}</button>{token && <button type="button" disabled={busy} className="rounded-xl border px-5 py-3" onClick={() => save(true)}>Unsubscribe from all marketing</button>}</div></form>}{error && <p role="alert" className="mt-4 text-red-600">{error}</p>}{notice && <p role="status" className="mt-4 text-emerald-600">{notice}</p>}</main><Footer /></>;
}
