import { Router } from "express";
import multer from "multer";
import { protect } from "../middlewares/auth.middleware.js";
import { hasPermission, requirePermission, requireAnyPermission } from "../utils/permissions.js";
import { jobRateLimit } from "../middlewares/jobRateLimit.middleware.js";
import * as c from "../controllers/communications.controller.js";
const router = Router();
const allow = (permission) => requirePermission(`communications.${permission}`);
const templateRead = (req, res, next) => ["templates.manage", "inbox.reply", "campaigns.create", "campaigns.send", "automations.manage"].some(p => hasPermission(req.user, `communications.${p}`)) ? next() : res.status(403).json({ success: false, message: "Template access required." });
const audienceRead = (req, res, next) => ["campaigns.read", "campaigns.send"].some(p => hasPermission(req.user, `communications.${p}`)) ? next() : res.status(403).json({ success: false, message: "Campaign access required." });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 4 } });
router.post("/webhooks/email", c.webhook);
router.get("/public/topics", c.publicTopics);
router.post("/public/subscribe", jobRateLimit({ windowMs: 3600000, max: 5 }), c.subscribe);
router.get("/public/preferences", c.getPreferences);
router.post("/public/preferences", c.updatePreferences);
router.post("/public/unsubscribe", c.unsubscribe);
router.use(protect);
router.get("/search", c.communicationsSearch);
router.get("/inbox", allow("inbox.read"), c.listInbox);
router.get("/inbox/users", allow("inbox.read"), c.assignableUsers);
router.get("/inbox/attachments/:assetId", allow("inbox.read"), c.downloadInboxAttachment);
router.get("/inbox/:id", allow("inbox.read"), c.getInbox);
router.patch("/inbox/:id/read", allow("inbox.read"), c.markInboxRead);
router.patch("/inbox/:id", allow("inbox.read"), c.updateInbox);
router.post("/inbox/:id/messages", allow("inbox.read"), allow("inbox.reply"), c.replyInbox);
router.post("/inbox/:id/attachments", allow("inbox.read"), allow("inbox.reply"), upload.array("files", 4), c.inboxAttachments);
router.post("/inbox/:id/share", allow("inbox.read"), requirePermission("messages.send"), c.shareInbox);
router.get("/subscribers", allow("subscribers.read"), c.listSubscribers);
router.patch("/subscribers/:id", allow("subscribers.manage"), c.manageSubscriber);
router.get("/templates", templateRead, c.listTemplates);
router.post("/templates", allow("templates.manage"), c.saveTemplate);
router.patch("/templates/:id", allow("templates.manage"), c.saveTemplate);
router.post("/preview", allow("templates.manage"), c.previewTemplate);
router.post("/test", allow("templates.manage"), jobRateLimit({ windowMs: 60000, max: 5 }), c.testEmail);
router.get("/campaigns", allow("campaigns.read"), c.listCampaigns);
router.post("/campaigns", allow("campaigns.create"), c.saveCampaign);
router.patch("/campaigns/:id", allow("campaigns.create"), c.saveCampaign);
router.post("/campaigns/:id/action", requireAnyPermission("communications.campaigns.create", "communications.campaigns.send"), c.campaignAction);
router.post("/audience", audienceRead, c.audienceCount);
router.post("/notify-content", allow("campaigns.send"), c.notifyContent);
router.get("/automations", allow("automations.manage"), c.listAutomations);
router.post("/automations", allow("automations.manage"), c.saveAutomation);
router.patch("/automations/:id", allow("automations.manage"), c.saveAutomation);
router.get("/transactional", allow("transactional.read"), c.listTransactional);
router.post("/transactional/:id/retry", allow("inbox.reply"), allow("transactional.read"), c.retryEmail);
router.get("/analytics", allow("analytics.read"), c.analytics);
router.get("/settings", allow("settings.manage"), c.getSettings);
router.patch("/settings", allow("settings.manage"), c.saveSettings);
export default router;
