"use client";
import { useEffect, useMemo, useState, useDeferredValue } from "react";
import { Search, LoaderCircle, X } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import SearchResult from "./SearchResult";
import { FILTER_LABELS, FILTERS, rankResults } from "@/lib/search/rankResults";
import { rememberSearch } from "@/lib/search/recentSearches";
import { trackSearch } from "@/lib/search/analytics";

export default function SearchPageClient() {
  const params = useSearchParams(); const router = useRouter();
  const [query, setQuery] = useState(params.get("q") || ""); const [type, setType] = useState(params.get("type") || "all"); const [technology, setTechnology] = useState(params.get("technology") || "all");
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const deferredQuery = useDeferredValue(query);
  useEffect(() => { fetch("/api/search-index").then((response) => { if (!response.ok) throw new Error(); return response.json(); }).then((body) => setItems(body.items || [])).catch(() => setError("Search is temporarily unavailable.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { const timer = setTimeout(() => { const next = new URLSearchParams(); if (query.trim()) next.set("q", query.trim()); if (type !== "all") next.set("type", type); if (technology !== "all") next.set("technology", technology); router.replace(`/search${next.size ? `?${next}` : ""}`, { scroll: false }); }, 180); return () => clearTimeout(timer); }, [query, type, technology, router]);
  useEffect(() => { if (!deferredQuery.trim()) return; const timer = setTimeout(() => rememberSearch(deferredQuery), 700); return () => clearTimeout(timer); }, [deferredQuery]);
  const technologies = useMemo(() => ["all", ...new Set(items.map((item) => item.technology).filter(Boolean).map(String))], [items]);
  const results = useMemo(() => rankResults(technology === "all" ? items : items.filter((item) => String(item.technology).toLowerCase() === technology.toLowerCase()), deferredQuery, { type, limit: 200 }), [items, deferredQuery, type, technology]);
  const selectFilter = (value) => { setType(value); trackSearch("search_filter_selected"); };
  return <section>
    <div className="mb-8"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Global search</p><h1 className="mt-2 font-outfit text-3xl font-black sm:text-5xl">Find what you want to learn</h1><p className="mt-3 text-sm text-zinc-600 dark:text-zinc-400">Courses, lessons, articles, interview questions, cheatsheets, and hands-on practice in one place.</p></div>
    <label htmlFor="search-page-input" className="sr-only">Search all asif.to content</label><div className="flex items-center gap-3 rounded-2xl bg-white dark:bg-zinc-900 px-4 shadow-lg ring-1 ring-zinc-200 dark:ring-zinc-800 focus-within:ring-2 focus-within:ring-blue-500"><Search className="h-5 w-5 text-zinc-400" /><input id="search-page-input" autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try “react effect api call”" className="min-w-0 flex-1 bg-transparent py-4 text-base outline-none" />{query && <button onClick={() => setQuery("")} aria-label="Clear search" className="rounded-lg p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800"><X className="h-4 w-4" /></button>}</div>
    <div role="tablist" className="mt-5 flex gap-2 overflow-x-auto pb-2" aria-label="Search result categories">{FILTERS.map((value) => <button key={value} role="tab" onClick={() => selectFilter(value)} aria-selected={type === value} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold focus-visible:ring-2 focus-visible:ring-blue-500 ${type === value ? "bg-blue-600 text-white" : "bg-zinc-100 dark:bg-zinc-900 text-zinc-600 dark:text-zinc-300"}`}>{FILTER_LABELS[value]}</button>)}</div>
    {technologies.length > 2 && <div className="mt-2"><label htmlFor="search-technology" className="mr-2 text-xs font-bold text-zinc-500">Technology</label><select id="search-technology" value={technology} onChange={(e) => setTechnology(e.target.value)} className="rounded-xl border border-zinc-200 bg-white px-3 py-2 text-xs dark:border-zinc-800 dark:bg-zinc-900"><option value="all">All technologies</option>{technologies.slice(1).sort().map((value) => <option key={value}>{value}</option>)}</select></div>}
    <div className="mt-8" aria-live="polite">{loading ? <div className="flex items-center justify-center gap-2 py-24 text-sm text-zinc-500"><LoaderCircle className="h-5 w-5 animate-spin" /> Loading search index…</div> : error ? <p className="rounded-2xl bg-red-50 p-8 text-center text-red-700 dark:bg-red-950/30">{error}</p> : !deferredQuery ? <div className="rounded-3xl border border-dashed border-zinc-300 p-12 text-center dark:border-zinc-700"><p className="font-bold">Start with a concept or technology</p><p className="mt-2 text-sm text-zinc-500">For example: state hook, next dynamic routes, or javscript closures.</p></div> : results.length ? <><p className="mb-3 text-xs font-bold text-zinc-500">{results.length} {results.length === 1 ? "result" : "results"} for “{deferredQuery}”</p><div role="list" className="grid gap-2 md:grid-cols-2">{results.map((item) => <div role="listitem" key={item.id} onClick={() => trackSearch("search_result_clicked")}><SearchResult item={item} query={deferredQuery} /></div>)}</div></> : <div className="rounded-3xl border border-dashed border-zinc-300 p-12 text-center dark:border-zinc-700"><p className="font-bold">No exact results for “{deferredQuery}”</p><p className="mt-2 text-sm text-zinc-500">Check the spelling, try fewer words, or clear the filters.</p><button onClick={() => { setType("all"); setTechnology("all"); }} className="mt-4 font-bold text-blue-600">Clear filters</button></div>}</div>
  </section>;
}
