"use client";
import { useEffect, useState } from "react";
import { ShieldAlert, Users, ExternalLink, X } from "lucide-react";
import api from "@/lib/axios";
import { toast } from "@/lib/toast";

const reasonLabel=(value)=>value?.replaceAll("_"," ");
export default function ModerationPage(){
  const [filter,setFilter]=useState("active"); const [data,setData]=useState({items:[],pagination:{}}); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState(null); const [caseData,setCaseData]=useState(null); const [busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);try{const response=await api.get("/community/moderation",{params:{reportStatus:filter,limit:30}});setData(response.data.data);}catch(e){toast.error(e.response?.data?.message||"Unable to load moderation queue");}finally{setLoading(false)}};
  useEffect(()=>{load()},[filter]);
  const open=async(item)=>{setSelected(item);setCaseData(null);try{const response=await api.get(`/community/moderation/${item.targetType}/${item.target._id}`);setCaseData(response.data.data);}catch(e){toast.error(e.response?.data?.message||"Unable to load reports")}};
  const action=async(actionName)=>{const reason=window.prompt("Optional moderation reason")||"";setBusy(true);try{await api.patch(`/community/moderation/${selected.targetType}/${selected.target._id}`,{action:actionName,reason});toast.success(`Content ${actionName} action completed`);await load();await open(selected);}catch(e){toast.error(e.response?.data?.message||"Moderation action failed")}finally{setBusy(false)}};
  const reports=async(disposition)=>{const reason=window.prompt("Optional resolution note")||"";setBusy(true);try{await api.patch(`/community/moderation/${selected.targetType}/${selected.target._id}/reports`,{disposition,reason});toast.success("Reports updated");await load();await open(selected);}catch(e){toast.error(e.response?.data?.message||"Unable to update reports")}finally{setBusy(false)}};
  return <div className="mx-auto max-w-7xl p-5 sm:p-8"><header className="mb-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-rose-600">Community safety</p><h1 className="mt-1 text-3xl font-black dark:text-white">Moderation queue</h1><p className="mt-2 text-sm text-zinc-500">Unique reporters, content state, report history, and every moderation action in one place.</p></header>
    <div className="mb-5 flex gap-2">{["active","resolved","dismissed"].map((value)=><button key={value} onClick={()=>setFilter(value)} className={`rounded-full px-4 py-2 text-xs font-bold capitalize ${filter===value?"bg-zinc-950 text-white dark:bg-white dark:text-zinc-950":"border border-zinc-200 dark:border-zinc-800"}`}>{value} reports</button>)}</div>
    <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-[#121215]">{loading?<p className="p-12 text-center text-sm text-zinc-500">Loading reports…</p>:data.items?.length?data.items.map((item)=><button key={`${item.targetType}:${item.target._id}`} onClick={()=>open(item)} className="flex w-full items-start gap-4 border-b border-zinc-100 p-5 text-left hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-900"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-rose-50 text-rose-600 dark:bg-rose-950/40"><ShieldAlert className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><b className="capitalize">{item.targetType}</b><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${item.target.status==="under_review"?"bg-amber-100 text-amber-800":"bg-zinc-100 text-zinc-600 dark:bg-zinc-800"}`}>{item.target.status}</span></span><span className="mt-1 block line-clamp-2 text-sm text-zinc-600 dark:text-zinc-300">{item.target.title||item.target.body}</span><span className="mt-2 flex flex-wrap gap-3 text-xs text-zinc-500"><span className="inline-flex items-center gap-1"><Users className="h-3.5 w-3.5"/>{item.uniqueReporterCount} unique reporters</span><span>{[...new Set(item.reasons)].map(reasonLabel).join(", ")}</span><span>Author: @{item.target.author?.username}</span></span></span></button>):<p className="p-12 text-center text-sm text-zinc-500">No {filter} report cases.</p>}</div>
    {selected&&<div className="fixed inset-0 z-100 flex justify-end bg-black/50" onClick={()=>setSelected(null)}><aside onClick={(e)=>e.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-zinc-950"><button onClick={()=>setSelected(null)} className="float-right rounded-full p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800"><X/></button><p className="text-xs font-black uppercase text-rose-600">{selected.targetType} report case</p><h2 className="mt-2 pr-12 text-2xl font-black dark:text-white">{selected.target.title||selected.target.post?.title||"Reported response"}</h2><div className="mt-5 rounded-2xl bg-zinc-100 p-4 text-sm whitespace-pre-wrap dark:bg-zinc-900">{selected.target.body}</div>{selected.target.code&&<pre className="mt-3 overflow-auto rounded-xl bg-black p-4 text-xs text-white">{selected.target.code}</pre>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>action("hide")} className="rounded-full bg-amber-500 px-4 py-2 text-xs font-bold text-white">Hide</button><button disabled={busy} onClick={()=>action("restore")} className="rounded-full bg-emerald-600 px-4 py-2 text-xs font-bold text-white">Restore</button><button disabled={busy} onClick={()=>action("remove")} className="rounded-full bg-rose-600 px-4 py-2 text-xs font-bold text-white">Remove</button><button disabled={busy} onClick={()=>reports("dismiss")} className="rounded-full border px-4 py-2 text-xs font-bold">Dismiss reports</button><button disabled={busy} onClick={()=>reports("resolve")} className="rounded-full border px-4 py-2 text-xs font-bold">Resolve reports</button>{(selected.target.slug||selected.target.post?.slug)&&<a target="_blank" rel="noreferrer" href={`${process.env.NEXT_PUBLIC_WEB_URL||"https://asif.to"}/community/${selected.target.slug||selected.target.post.slug}`} className="inline-flex items-center gap-1 rounded-full border px-4 py-2 text-xs font-bold">Open content <ExternalLink className="h-3.5 w-3.5"/></a>}</div>
      <h3 className="mt-8 text-lg font-black">Reports</h3>{!caseData?<p className="mt-3 text-sm text-zinc-500">Loading reporter details…</p>:<div className="mt-3 space-y-3">{caseData.reports.map((report)=><div key={report._id} className="rounded-xl border border-zinc-200 p-4 text-sm dark:border-zinc-800"><div className="flex justify-between gap-3"><b>@{report.reporter?.username||"deleted-user"}</b><span className="text-xs text-zinc-500">{new Date(report.createdAt).toLocaleString()}</span></div><p className="mt-1 capitalize">{reasonLabel(report.reason)} · <span className="text-zinc-500">{report.status}</span></p>{report.explanation&&<p className="mt-2 text-zinc-600 dark:text-zinc-400">{report.explanation}</p>}</div>)}</div>}
      <h3 className="mt-8 text-lg font-black">Moderation history</h3><div className="mt-3 space-y-2">{caseData?.actions?.length?caseData.actions.map((entry)=><div key={entry._id} className="rounded-xl bg-zinc-100 p-3 text-sm dark:bg-zinc-900"><b className="capitalize">{entry.action.replaceAll("_"," ")}</b> · {entry.source} · {entry.moderator?.username||"system"}<p className="mt-1 text-xs text-zinc-500">{new Date(entry.createdAt).toLocaleString()} {entry.reason&&`· ${entry.reason}`}</p></div>):<p className="text-sm text-zinc-500">No moderation actions yet.</p>}</div></aside></div>}
  </div>;
}
