"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, ExternalLink, Loader2, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { analyticsApi } from "@/lib/api";
import AnalyticsChart from "./AnalyticsChart";
import ReportTable from "./ReportTable";

const unwrap = (response) => response?.data?.data;
const presets = { "7 days": 7, "28 days": 28, "3 months": 90, "6 months": 180, "12 months": 365 };
const metricLabels = { clicks: "Total clicks", impressions: "Total impressions", ctr: "Average CTR", position: "Average position", organicVisitors: "Organic visitors", pageViews: "Page views", visitors: "Unique visitors", sessions: "Sessions", engagementTime: "Avg engagement time" };
const colors = { clicks: "border-blue-500", impressions: "border-violet-500", ctr: "border-amber-500", position: "border-pink-500", pageViews: "border-teal-500" };
function dates(days) { const end = new Date(); const start = new Date(); start.setDate(end.getDate() - days + 1); return { start: start.toISOString().slice(0,10), end: end.toISOString().slice(0,10) }; }
function format(key, value) { if (key === "ctr") return `${value.toFixed(1)}%`; if (key === "position") return value.toFixed(1); if (key === "engagementTime") return `${Math.round(value)}s`; return Math.round(value).toLocaleString(); }

export default function AnalyticsPage() {
  const [period, setPeriod] = useState("28 days"); const [range, setRange] = useState(dates(28)); const [overview, setOverview] = useState(null); const [content, setContent] = useState(null); const [sources, setSources] = useState([]); const [loading, setLoading] = useState(true); const [tab, setTab] = useState("queries"); const [report, setReport] = useState(null); const [search, setSearch] = useState(""); const [sort, setSort] = useState("clicks"); const [direction, setDirection] = useState("desc"); const [page, setPage] = useState(1); const [metrics, setMetrics] = useState({ clicks: true, impressions: true, ctr: false, position: false, pageViews: true }); const [contentTab, setContentTab] = useState("courses");
  const params = useMemo(() => range, [range]);
  const loadMain = useCallback(async () => { setLoading(true); const [a,b,c] = await Promise.all([analyticsApi.overview(params), analyticsApi.content(params), analyticsApi.sources(params)]); if (a.success) setOverview(unwrap(a)); else toast.error(a.error); if (b.success) setContent(unwrap(b)); if (c.success) setSources(unwrap(c) || []); setLoading(false); }, [params]);
  const loadReport = useCallback(async () => { const response = await analyticsApi.search(tab, { ...params, search, sort, direction, page, limit: 25 }); if (response.success) setReport(unwrap(response)); else toast.error(response.error); }, [tab, params, search, sort, direction, page]);
  useEffect(() => { loadMain(); }, [loadMain]); // eslint-disable-line react-hooks/set-state-in-effect
  useEffect(() => { const timer = setTimeout(loadReport, search ? 250 : 0); return () => clearTimeout(timer); }, [loadReport, search]);
  const setPreset = (name) => { setPeriod(name); if (presets[name]) setRange(dates(presets[name])); };
  const sync = async () => { const response = await analyticsApi.sync(); if (response.success) { toast.success("Search Console sync started"); setTimeout(loadMain, 1500); } else toast.error(response.error); };
  if (loading && !overview) return <div className="grid min-h-[70vh] place-items-center"><Loader2 className="animate-spin text-blue-600" size={32}/></div>;
  const connected = overview?.sync?.configured;
  return <div className="mx-auto flex max-w-[1500px] flex-col gap-6 p-4 sm:p-6 md:p-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-blue-600">Growth intelligence</p><h1 className="mt-1 text-3xl font-black">Search & site analytics</h1><p className="mt-1 text-sm text-zinc-500">Real Search Console performance and privacy-conscious first-party traffic.</p></div><div className="flex flex-wrap gap-2"><div className="flex flex-wrap rounded-2xl bg-zinc-100 p-1 dark:bg-zinc-900">{Object.keys(presets).map((name) => <button key={name} onClick={() => setPreset(name)} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === name ? "bg-white text-blue-600 shadow-sm dark:bg-zinc-950" : "text-zinc-500"}`}>{name}</button>)}<button onClick={() => setPeriod("Custom")} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === "Custom" ? "bg-white text-blue-600 dark:bg-zinc-950" : "text-zinc-500"}`}>Custom</button></div><Button onClick={sync} disabled={!connected || overview?.sync?.status === "syncing"}><RefreshCw size={15} className={overview?.sync?.status === "syncing" ? "animate-spin" : ""}/> Sync now</Button></div></header>
    {period === "Custom" && <div className="flex gap-2"><input type="date" value={range.start} onChange={(e) => setRange((r) => ({ ...r, start: e.target.value }))} className="rounded-xl border bg-transparent px-3 py-2"/><input type="date" value={range.end} onChange={(e) => setRange((r) => ({ ...r, end: e.target.value }))} className="rounded-xl border bg-transparent px-3 py-2"/></div>}
    {!connected && <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><AlertCircle className="shrink-0"/><div><strong>Search Console is not connected.</strong><p className="mt-1 text-xs opacity-80">Add the server environment variables described in env.example. First-party traffic will still appear as it is collected.</p></div></div>}
    <div className="flex items-center gap-2 text-xs text-zinc-500"><span className={`h-2 w-2 rounded-full ${overview?.sync?.status === "error" ? "bg-red-500" : "bg-emerald-500"}`}/>{overview?.sync?.lastSyncedAt ? `Last synced ${new Date(overview.sync.lastSyncedAt).toLocaleString()} · data through ${new Date(overview.sync.syncedThrough).toLocaleDateString()}` : "No Search Console sync yet"}{overview?.sync?.error && <span className="text-red-500"> · {overview.sync.error}</span>}</div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{Object.entries(metricLabels).map(([key,label]) => { const item = overview?.metrics?.[key] || { value: 0, change: 0 }; return <div key={key} className={`rounded-3xl border-t-4 bg-white p-5 shadow-sm dark:bg-zinc-900 ${colors[key] || "border-zinc-300"}`}><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{format(key, item.value)}</p><p className={`mt-1 flex items-center gap-1 text-xs font-bold ${item.change >= 0 ? "text-emerald-600" : "text-red-600"}`}>{item.change >= 0 ? <TrendingUp size={13}/> : <TrendingDown size={13}/>} {Math.abs(item.change).toFixed(1)}% vs previous</p></div>})}</section>
    <section><div className="mb-3 flex flex-wrap gap-2">{Object.keys(metrics).map((key) => <button key={key} onClick={() => setMetrics((m) => ({ ...m, [key]: !m[key] }))} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${metrics[key] ? "border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950" : "border-zinc-200 text-zinc-400 dark:border-zinc-800"}`}>{metricLabels[key] || key}</button>)}</div><AnalyticsChart data={overview?.trend || []} active={metrics}/></section>
    <section><div className="mb-3 flex gap-1 overflow-x-auto">{["queries","pages","countries","devices","appearance"].map((name) => <button key={name} onClick={() => { setTab(name); setPage(1); setSearch(""); }} className={`rounded-xl px-4 py-2 text-xs font-bold capitalize ${tab === name ? "bg-blue-600 text-white" : "bg-zinc-100 dark:bg-zinc-900"}`}>{name}</button>)}</div><ReportTable title={`Top ${tab}`} type={tab} report={report} search={search} onSearch={(value) => { setSearch(value); setPage(1); }} sort={sort} direction={direction} onSort={(key) => { if (sort === key) setDirection((d) => d === "desc" ? "asc" : "desc"); else { setSort(key); setDirection("desc"); } }} page={page} onPage={setPage} onOpen={(url) => window.open(url, "_blank")}/></section>
    <div className="grid gap-6 xl:grid-cols-3"><section className="xl:col-span-2 rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-black">Content performance</h2><div className="flex gap-1">{["courses","chapters","articles"].map((name) => <button key={name} onClick={() => setContentTab(name)} className={`rounded-lg px-3 py-1.5 text-xs font-bold capitalize ${contentTab === name ? "bg-blue-600 text-white" : "bg-zinc-100 dark:bg-zinc-900"}`}>{name}</button>)}</div></div><div className="space-y-2">{content?.content?.[contentTab]?.slice(0,10).map((item,index) => <a key={item.id} href={`https://asif.to${item.path}`} target="_blank" className="grid grid-cols-[30px_1fr_auto_auto] items-center gap-3 rounded-xl p-2 hover:bg-zinc-50 dark:hover:bg-zinc-900"><span className="text-xs font-black text-zinc-400">{index+1}</span><span className="truncate text-sm font-semibold">{item.title}</span><span className="text-xs font-bold text-blue-600">{item.clicks} clicks</span><span className={`text-xs font-bold ${item.growth >= 0 ? "text-emerald-600" : "text-red-600"}`}>{item.growth.toFixed(0)}%</span></a>)}</div></section><section className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><h2 className="mb-4 text-lg font-black">Traffic sources</h2><div className="space-y-3">{sources.slice(0,12).map((source,index) => <div key={`${source.source}-${source.referrer}-${index}`} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{source.source}</p><p className="truncate text-[10px] text-zinc-400">{source.medium}{source.campaign ? ` · ${source.campaign}` : ""}</p></div><span className="text-sm font-black">{source.views}</span></div>)}</div></section></div>
    <section className="rounded-3xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><h2 className="mb-4 text-lg font-black">SEO opportunities</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{content?.opportunities?.length ? content.opportunities.slice(0,18).map((item,index) => <a key={`${item.page}-${item.type}-${index}`} href={item.page} target="_blank" className="rounded-2xl border border-zinc-200 p-4 transition hover:border-blue-400 dark:border-zinc-800"><div className="flex items-center justify-between"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${item.impact === "high" ? "bg-red-50 text-red-600 dark:bg-red-950" : "bg-amber-50 text-amber-600 dark:bg-amber-950"}`}>{item.type}</span><ExternalLink size={13}/></div><p className="mt-3 truncate text-sm font-bold">{item.page}</p><p className="mt-1 text-xs text-zinc-500">{item.reason}</p></a>) : <p className="text-sm text-zinc-400">Opportunities appear after Search Console data is synced.</p>}</div></section>
  </div>;
}
