"use client";
// ASIF_QUESTION_LEARNING_MAPPING_V1
import Link from "next/link";
import { BookOpen, Brain, Hammer, Layers } from "lucide-react";
export default function ChapterLearningActivitiesEditor({ courseId, chapterId, form, setForm }) {
  const setField=(key,value)=>setForm((c)=>({...c,[key]:value}));
  const href=`/quiz?courseId=${encodeURIComponent(courseId||"")}&type=quiz&mapping=mapped${chapterId?`&chapterId=${encodeURIComponent(chapterId)}`:""}`;
  return <section className="space-y-5 rounded-4xl border border-zinc-200/60 bg-white p-5 dark:border-zinc-800/60 dark:bg-zinc-950">
    <div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-blue-600">Course learning flow</p><h2 className="mt-1 text-base font-semibold">Learn → Revise → Practice → Build</h2><p className="mt-1 text-sm text-muted-foreground">Learn is the chapter. Revision and Practice now come from Question Bank mappings, so question IDs are not duplicated on Chapter.</p></div>
    <div className="grid gap-3 md:grid-cols-4"><Stage icon={BookOpen} label="Learn" text="Chapter content"/><Stage icon={Layers} label="Revise" text="Mapped flashcards"/><Stage icon={Brain} label="Practice" text="Mapped quiz questions"/><Stage icon={Hammer} label="Build" text={form.buildEnabled?"Configured":"Optional"}/></div>
    <div className="rounded-3xl bg-blue-50 p-4 dark:bg-blue-500/10"><p className="text-xs font-bold">Revision & Practice mapping</p><p className="mt-1 text-[11px] leading-5 text-zinc-500">Assign course, category and chapter on each question. The learner stage appears only when mapped content exists.</p><Link href={href} className="mt-3 inline-flex rounded-full bg-blue-600 px-4 py-2 text-[11px] font-black text-white">Open Question Bank →</Link></div>
    <div className="rounded-3xl bg-zinc-50 p-4 dark:bg-zinc-900/60"><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={Boolean(form.buildEnabled)} onChange={(e)=>setField("buildEnabled",e.target.checked)}/> Add a Build challenge</label>{form.buildEnabled&&<div className="mt-4 grid gap-3"><input value={form.buildTitle||""} onChange={(e)=>setField("buildTitle",e.target.value)} placeholder="Build challenge title" className="h-11 rounded-2xl border-0 bg-white px-4 text-sm dark:bg-zinc-950"/><textarea rows={3} value={form.buildDescription||""} onChange={(e)=>setField("buildDescription",e.target.value)} placeholder="What should the learner build?" className="rounded-2xl border-0 bg-white px-4 py-3 text-sm dark:bg-zinc-950"/><textarea rows={4} value={form.buildRequirements||""} onChange={(e)=>setField("buildRequirements",e.target.value)} placeholder="One requirement per line" className="rounded-2xl border-0 bg-white px-4 py-3 text-sm dark:bg-zinc-950"/><input type="number" min="0" value={form.buildEstimatedMinutes||0} onChange={(e)=>setField("buildEstimatedMinutes",Number(e.target.value)||0)} className="h-10 w-32 rounded-xl border-0 bg-white px-3 dark:bg-zinc-950"/></div>}</div>
  </section>;
}
function Stage({icon:Icon,label,text}) { return <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-3 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-600"/><span className="text-xs font-black">{label}</span></div><p className="mt-2 text-[11px] text-zinc-500">{text}</p></div>; }
