/**
 * ISO 3166-1 alpha-3 & alpha-2 to Full Country Name resolution.
 */

const ALPHA3_TO_NAME = {
  afg: "Afghanistan",
  alb: "Albania",
  dza: "Algeria",
  and: "Andorra",
  ago: "Angola",
  arg: "Argentina",
  arm: "Armenia",
  aus: "Australia",
  aut: "Austria",
  aze: "Azerbaijan",
  bhs: "Bahamas",
  bhr: "Bahrain",
  bgd: "Bangladesh",
  arm: "Armenia",
  bel: "Belgium",
  blz: "Belize",
  ben: "Benin",
  btn: "Bhutan",
  bol: "Bolivia",
  bih: "Bosnia and Herzegovina",
  bwa: "Botswana",
  bra: "Brazil",
  brn: "Brunei",
  bgr: "Bulgaria",
  bfa: "Burkina Faso",
  bdi: "Burundi",
  khm: "Cambodia",
  cmr: "Cameroon",
  can: "Canada",
  chl: "Chile",
  chn: "China",
  col: "Colombia",
  cog: "Congo",
  cri: "Costa Rica",
  hrv: "Croatia",
  cub: "Cuba",
  cyp: "Cyprus",
  cze: "Czech Republic",
  dnk: "Denmark",
  dom: "Dominican Republic",
  ecu: "Ecuador",
  egy: "Egypt",
  slv: "El Salvador",
  est: "Estonia",
  eth: "Ethiopia",
  fin: "Finland",
  fra: "France",
  geo: "Georgia",
  deu: "Germany",
  gha: "Ghana",
  grc: "Greece",
  gtm: "Guatemala",
  hkg: "Hong Kong",
  hun: "Hungary",
  isl: "Iceland",
  ind: "India",
  idn: "Indonesia",
  irn: "Iran",
  irq: "Iraq",
  irl: "Ireland",
  isr: "Israel",
  ita: "Italy",
  jam: "Jamaica",
  jpn: "Japan",
  jor: "Jordan",
  kaz: "Kazakhstan",
  ken: "Kenya",
  kwt: "Kuwait",
  kgz: "Kyrgyzstan",
  lao: "Laos",
  lva: "Latvia",
  lbn: "Lebanon",
  lby: "Libya",
  ltu: "Lithuania",
  lux: "Luxembourg",
  mac: "Macau",
  mys: "Malaysia",
  mdv: "Maldives",
  mlt: "Malta",
  mex: "Mexico",
  mda: "Moldova",
  mco: "Monaco",
  mng: "Mongolia",
  mar: "Morocco",
  moz: "Mozambique",
  mmr: "Myanmar",
  nam: "Namibia",
  npl: "Nepal",
  nld: "Netherlands",
  nzl: "New Zealand",
  nic: "Nicaragua",
  nga: "Nigeria",
  prk: "North Korea",
  nor: "Norway",
  omn: "Oman",
  pak: "Pakistan",
  pse: "Palestine",
  pan: "Panama",
  pry: "Paraguay",
  per: "Peru",
  phl: "Philippines",
  pol: "Poland",
  prt: "Portugal",
  qat: "Qatar",
  rou: "Romania",
  rus: "Russia",
  rwa: "Rwanda",
  sau: "Saudi Arabia",
  sen: "Senegal",
  srb: "Serbia",
  sgp: "Singapore",
  svk: "Slovakia",
  svn: "Slovenia",
  som: "Somalia",
  zaf: "South Africa",
  kor: "South Korea",
  esp: "Spain",
  lka: "Sri Lanka",
  sdn: "Sudan",
  swe: "Sweden",
  che: "Switzerland",
  syr: "Syria",
  twn: "Taiwan",
  tjk: "Tajikistan",
  tza: "Tanzania",
  tha: "Thailand",
  tun: "Tunisia",
  tur: "Turkey",
  uga: "Uganda",
  ukr: "Ukraine",
  are: "United Arab Emirates",
  gbr: "United Kingdom",
  usa: "United States",
  ury: "Uruguay",
  uzb: "Uzbekistan",
  ven: "Venezuela",
  vnm: "Vietnam",
  yem: "Yemen",
  zmb: "Zambia",
  zwe: "Zimbabwe",
};

export function getFullCountryName(codeOrName) {
  if (!codeOrName) return "Unknown";
  const raw = String(codeOrName).trim();
  const lower = raw.toLowerCase();

  // Direct lookup from Alpha-3 map
  if (ALPHA3_TO_NAME[lower]) {
    return ALPHA3_TO_NAME[lower];
  }

  // Alpha-2 code fallback using Intl.DisplayNames
  if (raw.length === 2) {
    try {
      const regionNames = new Intl.DisplayNames(["en"], { type: "region" });
      const name = regionNames.of(raw.toUpperCase());
      if (name) return name;
    } catch {
      // ignore
    }
  }

  // If already a full name or unrecognized
  return raw;
}
