import Image from "next/image";
import Link from "next/link";
import { BookOpen, CheckCircle2, Code2, ExternalLink, FileText, Github, Linkedin, UserRound } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { authorIdentity } from "@/lib/authorIdentity";
import { assetUrl } from "@/lib/seo";

const workflow = [
  ["Research", "Start with primary documentation, specifications, and the behavior of the current tool or framework version."],
  ["Implementation", "Build the example in the same stack used by asif.to and resolve the practical integration details."],
  ["Testing", "Run the example or relevant project checks and verify that the explanation matches the observed behavior."],
  ["Writing", "Turn the implementation into focused steps, explain decisions, and remove details that do not help the reader."],
  ["Review", "Re-read for technical consistency, clear prerequisites, working code, and honest limitations."],
  ["Updates", "Revise content when the underlying code, APIs, or documented behavior changes."],
];

export default function AsifAuthorProfile({ profile, courses = [], articles = [] }) {
  const links = [
    ["GitHub", profile?.socials?.github || process.env.NEXT_PUBLIC_AUTHOR_GITHUB_URL, Github],
    ["LinkedIn", profile?.socials?.linkedin || process.env.NEXT_PUBLIC_AUTHOR_LINKEDIN_URL, Linkedin],
    ["Portfolio", profile?.socials?.website || process.env.NEXT_PUBLIC_AUTHOR_PORTFOLIO_URL, ExternalLink],
  ].filter(([, url]) => /^https?:\/\//i.test(url || ""));
  return <div className="min-h-screen bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100"><Header/><main className="mx-auto max-w-6xl px-4 pb-20 pt-24 sm:px-6 sm:pt-28">
    <nav className="mb-7 flex items-center gap-2 text-xs font-bold text-zinc-400"><Link href="/">Home</Link><span>/</span><Link href="/about">About</Link><span>/</span><span className="text-zinc-700 dark:text-zinc-200">Asif</span></nav>
    <section className="overflow-hidden rounded-[2.5rem] border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 sm:p-10"><div className="flex flex-col gap-7 md:flex-row md:items-center">
      <div className="relative grid h-28 w-28 shrink-0 place-items-center overflow-hidden rounded-3xl bg-blue-600 text-white">{profile?.avatar ? <Image src={assetUrl(profile.avatar)} alt="Asif" fill className="object-cover" unoptimized/> : <UserRound className="h-14 w-14"/>}</div>
      <div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-[.22em] text-blue-600">Author and maintainer of asif.to</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-6xl">Asif</h1><p className="mt-2 text-lg font-bold text-zinc-600 dark:text-zinc-300">Full-Stack JavaScript Developer</p><p className="mt-4 max-w-3xl leading-relaxed text-zinc-500 dark:text-zinc-400">I build and maintain asif.to and write its practical programming tutorials. My work in this repository covers the Next.js public site and admin tools, Node.js and Express APIs, MongoDB data models, authentication, course and article publishing, learning features, analytics, and deployment configuration.</p>
      <div className="mt-5 flex flex-wrap gap-2">{links.map(([label,url,Icon]) => <a key={label} href={url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full border border-zinc-200 px-4 py-2 text-xs font-bold hover:border-blue-500 hover:text-blue-600 dark:border-zinc-700"><Icon className="h-4 w-4"/>{label}</a>)}{!links.length && <p className="rounded-xl bg-amber-50 px-3 py-2 text-xs text-amber-700 dark:bg-amber-950/30 dark:text-amber-300">GitHub, LinkedIn, and portfolio URLs have not been provided yet.</p>}</div></div>
    </div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><Code2 className="h-6 w-6 text-blue-600"/><h2 className="mt-4 text-2xl font-black">Development experience represented here</h2><p className="mt-3 text-sm leading-7 text-zinc-500">The verifiable experience described on this page is the development and ongoing maintenance of asif.to. It is a full-stack learning product with public content, an authenticated learning experience, editorial administration, database-backed courses and articles, quizzes, revision tools, analytics, and SEO infrastructure.</p><h3 className="mt-6 text-sm font-black">Technologies used</h3><div className="mt-3 flex flex-wrap gap-2">{authorIdentity.technologies.map((tech) => <span key={tech} className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{tech}</span>)}</div></div>
    <div className="rounded-3xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><BookOpen className="h-6 w-6 text-emerald-600"/><h2 className="mt-4 text-2xl font-black">Why I created asif.to</h2><p className="mt-3 text-sm leading-7 text-zinc-500">asif.to is designed to make programming concepts easier to understand and easier to revisit. The aim is to combine step-by-step courses with concise reference material, examples, quizzes, and revision tools so readers can move between learning and practice without unnecessary filler.</p><h3 className="mt-6 text-sm font-black">Areas of focus</h3><ul className="mt-3 space-y-2 text-sm text-zinc-500">{["Full-stack JavaScript application architecture", "React and Next.js interfaces", "Node.js, Express, MongoDB, and Mongoose APIs", "Redux Toolkit and RTK Query data flows", "Content platforms, authentication, SEO, and deployment workflows"].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500"/>{item}</li>)}</ul></div></section>
    <section className="mt-8 rounded-[2.5rem] border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 sm:p-9"><p className="text-[11px] font-black uppercase tracking-[.2em] text-blue-600">Editorial methodology</p><h2 className="mt-2 text-3xl font-black">How content is created</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-500">Tutorials are treated as maintainable technical documentation: the explanation should be traceable to primary documentation and practical behavior, while limitations and prerequisites should remain visible.</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{workflow.map(([title,text],index) => <div key={title} className="rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-950"><span className="text-xs font-black text-blue-600">0{index+1}</span><h3 className="mt-2 font-black">{title}</h3><p className="mt-2 text-xs leading-6 text-zinc-500">{text}</p></div>)}</div></section>
    <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-blue-600">Published work</p><h2 className="mt-2 text-3xl font-black">Courses and articles</h2></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{courses.slice(0,6).map((course) => <Link key={course._id} href={`/courses/${course.slug}`} className="rounded-3xl border border-zinc-200 bg-white p-5 hover:border-blue-400 dark:border-zinc-800 dark:bg-zinc-900"><BookOpen className="h-5 w-5 text-blue-600"/><h3 className="mt-4 font-black">{course.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-zinc-500">{course.subtitle}</p></Link>)}{articles.slice(0,6).map((article) => <Link key={article._id} href={`/articles/${article.slug}-${article._id}`} className="rounded-3xl border border-zinc-200 bg-white p-5 hover:border-blue-400 dark:border-zinc-800 dark:bg-zinc-900"><FileText className="h-5 w-5 text-emerald-600"/><h3 className="mt-4 font-black">{article.title}</h3><p className="mt-2 text-xs text-zinc-500">Published {new Date(article.createdAt).toLocaleDateString()}</p></Link>)}</div>{!courses.length && !articles.length && <p className="mt-5 text-sm text-zinc-500">Published work will appear here when it is available from the content API.</p>}</section>
  </main><Footer/></div>;
}
