"use client";
import { useState } from "react";
import Link from "next/link";
import { CheckCircle2, CornerDownRight, Trash2, Pencil } from "lucide-react";
import { toast } from "sonner";
import { useAppSelector } from "@/lib/store/hooks";
import { useGetCommunityPostQuery, useCreateCommunityCommentMutation, useUpdateCommunityCommentMutation, useDeleteCommunityCommentMutation, useAcceptCommunityCommentMutation, useDeleteCommunityPostMutation, useUpdateCommunityPostMutation } from "@/lib/api/communityApi";
import ReportButton from "./ReportButton";
import { TYPE_LABELS } from "./communityConstants";

const same=(a,b)=>String(a||"")===String(b||"");
function Comment({comment,post,currentUser,onReply,onRefresh}){
  const mine=same(comment.author?._id,currentUser?._id); const accepted=same(post.acceptedComment,comment._id); const [editing,setEditing]=useState(false); const [body,setBody]=useState(comment.body);
  const [update,{isLoading}]=useUpdateCommunityCommentMutation(); const [remove]=useDeleteCommunityCommentMutation(); const [accept]=useAcceptCommunityCommentMutation();
  const save=async()=>{try{await update({commentId:comment._id,body}).unwrap();setEditing(false);onRefresh();}catch(e){toast.error(e?.data?.message||"Unable to edit response")}};
  const del=async()=>{if(!confirm("Delete this response?"))return;try{await remove(comment._id).unwrap();onRefresh();}catch(e){toast.error(e?.data?.message||"Unable to delete response")}};
  const mark=async()=>{try{await accept({postId:post._id,commentId:comment._id}).unwrap();toast.success("Accepted solution marked");onRefresh();}catch(e){toast.error(e?.data?.message||"Unable to accept response")}};
  return <div id={`comment-${comment._id}`} className={`rounded-2xl border p-4 ${accepted?"border-emerald-400 bg-emerald-50/40 dark:bg-emerald-950/20":"border-zinc-200 dark:border-zinc-800"}`}>
    <div className="flex flex-wrap items-center gap-2 text-xs text-zinc-500"><Link href={`/${comment.author?.username}`} className="font-bold text-zinc-800 dark:text-zinc-200">{comment.author?.fullName||"Deleted user"}</Link><span>· {new Date(comment.createdAt).toLocaleString()}</span>{comment.editedAt&&<span>· edited</span>}{accepted&&<span className="ml-auto inline-flex items-center gap-1 font-bold text-emerald-600"><CheckCircle2 className="h-4 w-4"/>Accepted solution</span>}</div>
    {editing?<div className="mt-3"><textarea value={body} onChange={(e)=>setBody(e.target.value)} className="w-full rounded-xl border bg-transparent p-3 text-sm dark:border-zinc-700"/><div className="mt-2 flex gap-2"><button disabled={isLoading} onClick={save} className="rounded-full bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">Save</button><button onClick={()=>setEditing(false)} className="text-xs font-bold">Cancel</button></div></div>:<p className="mt-3 whitespace-pre-wrap text-sm leading-6">{comment.body}</p>}
    {comment.code&&<pre className="mt-3 overflow-auto rounded-xl bg-zinc-950 p-4 text-xs text-zinc-100"><code>{comment.code}</code></pre>}
    {comment.status==="published"&&<div className="mt-3 flex flex-wrap gap-4">{!comment.parent&&<button onClick={()=>onReply(comment)} className="inline-flex items-center gap-1 text-xs font-bold text-blue-600"><CornerDownRight className="h-3.5 w-3.5"/>Reply</button>}{mine&&<><button onClick={()=>setEditing(true)} className="inline-flex items-center gap-1 text-xs text-zinc-500"><Pencil className="h-3 w-3"/>Edit</button><button onClick={del} className="inline-flex items-center gap-1 text-xs text-rose-600"><Trash2 className="h-3 w-3"/>Delete</button></>}{same(post.author?._id,currentUser?._id)&&["question","help"].includes(post.type)&&!post.acceptedComment&&!comment.parent&&!mine&&<button onClick={mark} className="text-xs font-bold text-emerald-600">Mark accepted</button>}{!mine&&<ReportButton targetType="comment" targetId={comment._id}/>}</div>}
    {comment.replies?.length>0&&<div className="ml-3 mt-4 space-y-3 border-l-2 border-zinc-200 pl-3 dark:border-zinc-700">{comment.replies.map((reply)=><Comment key={reply._id} comment={{...reply,parent:comment._id}} post={post} currentUser={currentUser} onReply={onReply} onRefresh={onRefresh}/>)}</div>}
  </div>;
}

export default function CommunityPostDetail({slug}){
  const {data,isLoading,isError,refetch}=useGetCommunityPostQuery(slug); const result=data?.data; const post=result?.post; const comments=result?.comments||[];
  const currentUser=useAppSelector((s)=>s.auth.user); const authenticated=useAppSelector((s)=>s.auth.isAuthenticated);
  const [body,setBody]=useState(""); const [parent,setParent]=useState(null); const [create,{isLoading:submitting}]=useCreateCommunityCommentMutation(); const [removePost]=useDeleteCommunityPostMutation(); const [updatePost]=useUpdateCommunityPostMutation(); const [editing,setEditing]=useState(false); const [edit,setEdit]=useState({title:"",body:""});
  if(isLoading)return <p className="py-24 text-center text-sm text-zinc-500">Loading discussion…</p>; if(isError||!post)return <p className="py-24 text-center font-bold">This discussion is unavailable.</p>;
  const mine=same(post.author?._id,currentUser?._id);
  const respond=async(e)=>{e.preventDefault();try{await create({postId:post._id,body,parentId:parent?._id}).unwrap();setBody("");setParent(null);refetch();}catch(error){toast.error(error?.data?.message||"Unable to add response")}};
  const delPost=async()=>{if(!confirm("Delete this post? It will no longer be public."))return;try{await removePost(slug).unwrap();location.href="/community";}catch(e){toast.error(e?.data?.message||"Unable to delete post")}};
  const savePost=async()=>{try{await updatePost({slug,...edit}).unwrap();setEditing(false);refetch();}catch(e){toast.error(e?.data?.message||"Unable to edit post")}};
  return <div>
    {post.status!=="published"&&mine&&<div className="mb-5 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{post.status==="removed"?"This post was removed for violating community guidelines.":post.status==="deleted_by_author"?"You deleted this post.":"This post is temporarily hidden while it is being reviewed."}</div>}
    <article className="rounded-3xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 sm:p-8"><div className="flex flex-wrap items-center gap-2 text-xs text-zinc-500"><Link href={`/${post.author.username}`} className="font-bold text-zinc-900 dark:text-white">{post.author.fullName}</Link><span>· {new Date(post.createdAt).toLocaleString()}</span><span className="ml-auto rounded-full bg-blue-50 px-3 py-1 font-bold text-blue-700 dark:bg-blue-950 dark:text-blue-300">{TYPE_LABELS[post.type]}</span></div>
      {editing?<div className="mt-5 space-y-3"><input value={edit.title} onChange={(e)=>setEdit({...edit,title:e.target.value})} className="w-full rounded-xl border bg-transparent p-3 text-xl font-bold"/><textarea rows={7} value={edit.body} onChange={(e)=>setEdit({...edit,body:e.target.value})} className="w-full rounded-xl border bg-transparent p-3"/><button onClick={savePost} className="rounded-full bg-blue-600 px-4 py-2 text-sm font-bold text-white">Save changes</button><button onClick={()=>setEditing(false)} className="ml-3 text-sm font-bold">Cancel</button></div>:<><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">{post.title}</h1><p className="mt-5 whitespace-pre-wrap text-base leading-7 text-zinc-700 dark:text-zinc-300">{post.body}</p>{post.code&&<pre className="mt-5 overflow-auto rounded-2xl bg-zinc-950 p-5 text-sm text-zinc-100"><code>{post.code}</code></pre>}</>}
      {post.relatedResource&&<Link href={post.relatedResource.url} className="mt-5 block rounded-2xl bg-blue-50 p-4 text-sm font-bold text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">Related {post.relatedResource.kind.replaceAll("_"," ")} · {post.relatedResource.title}</Link>}
      <div className="mt-5 flex gap-4 border-t border-zinc-100 pt-4 dark:border-zinc-800">{mine&&post.viewerCanEdit&&<><button onClick={()=>{setEdit({title:post.title,body:post.body});setEditing(true)}} className="text-xs font-bold text-blue-600">Edit post</button><button onClick={delPost} className="text-xs font-bold text-rose-600">Delete post</button></>}{!mine&&post.status==="published"&&<ReportButton targetType="post" targetId={post._id}/>}</div>
    </article>
    {post.status==="published"&&<section className="mt-8"><h2 className="text-2xl font-black">Responses <span className="text-zinc-400">{post.commentCount}</span></h2>{authenticated?<form onSubmit={respond} className="mt-4 rounded-2xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">{parent&&<div className="mb-2 flex justify-between rounded-lg bg-blue-50 p-2 text-xs text-blue-700"><span>Replying to {parent.author?.fullName}</span><button type="button" onClick={()=>setParent(null)}>Cancel</button></div>}<textarea required minLength={2} maxLength={10000} value={body} onChange={(e)=>setBody(e.target.value)} rows={4} placeholder="Add a helpful response…" className="w-full resize-y bg-transparent text-sm outline-none"/><div className="mt-3 flex justify-end"><button disabled={submitting} className="rounded-full bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{submitting?"Posting…":"Post response"}</button></div></form>:<p className="mt-4 rounded-2xl border border-dashed p-5 text-sm"><Link href="/login" className="font-bold text-blue-600">Sign in</Link> to respond.</p>}<div className="mt-5 space-y-4">{comments.length?comments.map((comment)=><Comment key={comment._id} comment={comment} post={post} currentUser={currentUser} onReply={setParent} onRefresh={refetch}/>):<p className="py-8 text-center text-sm text-zinc-500">No responses yet. Add the first useful thought.</p>}</div></section>}
  </div>;
}
